#!/usr/bin/bash
set -euo pipefail

width=$1
height=${width}

mkdir -p images
convert \
  -gravity center \
  -font Helvetica \
  -pointsize "$((width / 4 * 3))" \
  -background "#429DEB" \
  -fill "#FFFFFF" \
  -size "${width}x${height}" \
  label:t \
  "images/icon${width}.png"
