name: release

on:
  push:
    branches:
      - main
    paths:
      - CHANGELOG.md
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    uses: r7kamura/workflows/.github/workflows/changelog-tag-release.yml@main
